SELECT DEPARTMENT_NAME,locations.LOCATION_ID,STREET_ADDRESS,CITY,STATE_PROVINCE,COUNTRY_NAME
FROM (locations
INNER JOIN departments
ON departments.LOCATION_ID=locations.LOCATION_ID)
	LEFT OUTER JOIN countries
    ON locations.COUNTRY_ID = countries.COUNTRY_ID;