SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,SALARY
FROM employees
WHERE SALARY in (SELECT MIN(SALARY)
	FROM employees
	INNER JOIN departments
	ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID
	GROUP BY DEPARTMENT_NAME);