SELECT CONCAT(FIRST_NAME,', ',LAST_NAME) as EMPLOYEE_NAME,departments.DEPARTMENT_NAME
FROM employees
LEFT OUTER JOIN departments
ON departments.DEPARTMENT_ID=employees.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'IT';