SELECT departments.DEPARTMENT_NAME,COUNT(*) as EMPLOYEE_NUMBER_OF_DEPARTMENT,AVG(SALARY)
FROM employees
LEFT OUTER JOIN departments
ON employees.DEPARTMENT_ID = departments.DEPARTMENT_ID
GROUP BY departments.DEPARTMENT_NAME
HAVING EMPLOYEE_NUMBER_OF_DEPARTMENT>10;